services:
  - type: web
    name: rasmalai-core
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:40Kunal%40Ugale60@db.uzfhsghhbpdnhjofedzd.supabase.co:5432/postgres
      - key: AUTO_IRRIGATION_MOISTURE_THRESHOLD
        value: "40.0"
      - key: MIN_WATER_TANK_LEVEL
        value: "15.0"
